/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package koch;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author 348676487
 */
public class Panel extends javax.swing.JPanel {

    /**
     * Creates new form Panel
     */
    public Panel() {
        initComponents();
    }

    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        koch(g, 1, this.getWidth() / 2, this.getHeight() / 2, 500);
    }

    public void koch(Graphics g, int n, int x, int y, int size) {
        //Draw an h shape
        piece(g, x, y, size);
        //Recurse until n is 0
        if (n > 0) {
            //left
            koch(g, n - 1, x - size / 3, y, size / 3);
            //left angle
            koch(g, n - 1, x - size / 12, (int) (y - (size * Math.sqrt(3) / 12)), size / 3);
            //right angle
            koch(g, n - 1, x + size / 12, (int) (y - (size * Math.sqrt(3) / 12)), size / 3);
            //right
            koch(g, n - 1, x + size / 3, y, size / 3);
        }
    }

    public void piece(Graphics g, int x, int y, int size) {
        g.setColor(Color.BLACK);
        //base
        g.drawLine(x - size / 2, y, x + size / 2, y);
        //left angle
        g.drawLine(x - size / 6, y, x, (int) (y - (size * Math.sqrt(3) / 6)));
        //right angle
        g.drawLine(x + size / 6, y, x, (int) (y - (size * Math.sqrt(3) / 6)));

        //invisible middle
        g.setColor(new Color(214, 217, 223));
        g.drawLine(x - size / 6, y, x + size / 6, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
